chat/urls.py
from django.urls import path
from .views import *
#from chat import urls
from django.conf import settings
from django.conf.urls.static import static

app_name = 'chat'
urlpatterns = [
    path('', rooms, kwargs={'type_room':"Private"},  name='private_rooms'),
    path('public', rooms, kwargs={'type_room':"Public"},  name='public_rooms'),
    path('group', rooms, kwargs={'type_room':"Group"},  name='group_rooms'),
    path('private/<slug:slug>', room, kwargs={'type_room':"Private"}, name='room'),
    path('public/<slug:slug>', room, kwargs={'type_room':"Public"}, name='room'),
    path('group/<slug:slug>', room, kwargs={'type_room':"Group"}, name='room'),
    path('update/<slug:slug>', update_room,  name='update_room'),
    path('delete/<slug:slug>', delete_room,  name='delete_room'),



    path('postal', postal,  name='postal'),
] 

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

myProject/urls.py
from django.contrib import admin
from django.urls import path, include
#from chat import urls


urlpatterns = [
    path('', include('main.urls')),
    path('accounts/', include('user_auth.urls')), #google authentication
    path('', include('django.contrib.auth.urls')),#"local" authentication
    path('chat/', include('chat.urls', namespace='chat')), # chat application
    path('automail/', include('automail.urls', namespace='email')), # email application
    path('chess/', include('chess.urls', namespace='chess')), # chess application
    path('admin/', admin.site.urls),
]

chat/models.py
from django.contrib.auth.models import User
from django.db import models
import django.utils.timezone
# Create your models here.

class AccountChat(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	profile_picture = models.CharField(max_length=100000, blank=True, null=True)

	def __str__(self):
		return self.user.username


class Room(models.Model):
	ROOM_CHOICES = (
        ("Public", "Public"),
        ("Private", "Private"),
        ("Group", "Group")
    )
	name = models.CharField(max_length=255)
	room_picture = models.FileField(upload_to='room_pictures', default='room_pictures/default.jpeg')
	slug = models.SlugField(unique=True)
	room_type = models.TextField(max_length=7, choices=ROOM_CHOICES, blank=False, null=False) # Public, Private, Group
	authorized_users = models.TextField(max_length=10000, null=True) #Users can use room

	def __str__(self):
		return self.name

class Message(models.Model):
	room = models.ForeignKey(Room, related_name='messages', on_delete=models.CASCADE)
	user = models.ForeignKey(User, related_name='messages', on_delete=models.CASCADE)
	content = models.TextField()
	date_added = models.DateTimeField(default=django.utils.timezone.now)#auto_now_add=True)

	def __str__(self):
		return self.room.name + " " + str(self.date_added)

	class Meta:
		ordering = ('date_added', )

chat/forms.py
from django import forms

from .models import Room


class RoomForm(forms.ModelForm):
	name_authorized = forms.CharField(max_length=40)
	class Meta:
		model = Room
		fields = [
			'name',
			'room_picture',
			'slug',
			'room_type',
			'authorized_users',
		]

chat/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from .models import Message, Room
from .forms import RoomForm
from django.db import IntegrityError
from django.contrib import messages
import re 
# Create your views here.


@login_required
def rooms(request, type_room):
	form = RoomForm()
	tmp = 'This name has already been used!'
	if request.method == 'POST':
		try:
			form = RoomForm(request.POST, request.FILES)
			if form.is_valid():
				post = form.save(commit=False)
				temp = form.cleaned_data["name"]
				temp = re.sub(u'[!@#$%¨&*(:)+=-?\'\"]', '', temp)
				temp = temp.lower().strip().split(" ")
				temp = '_'.join(temp)
				post.slug = f'{request.user.id}_{temp}'
				if (form.cleaned_data["name_authorized"] != "None"):
					temp = [form.cleaned_data["authorized_users"],form.cleaned_data["name_authorized"]]
					post.authorized_users = f'{temp[0]}{temp[1]},'
				post.save()
		except IntegrityError as e: 
			messages.warning(request, 'This name has already been used!')
	if (type_room == "Private"):
		rooms = Room.objects.filter(room_type__contains=type_room, authorized_users__contains=f'{request.user.username},')
	elif (type_room == "Group"):
		rooms = Room.objects.filter(room_type__contains=type_room, authorized_users__contains=f'{request.user.username},')
	else:
		rooms = Room.objects.filter(room_type__contains=type_room)
	return render(request, 'chat/rooms.html', {'rooms':rooms, 'form' : form, 'tmp': tmp, 'type_room':type_room})




@login_required
def room(request, slug, type_room):

	room = Room.objects.get(slug=slug)
	msg = Message.objects.filter(room=room)[0:25]
	temp2 = ''
	for x in range(0, len(msg)):
		if msg[x].user.username == temp2:
			temp2 = msg[x].user.username
			msg[x].user.username = f'not {msg[x].user.username}'
		else:
			temp2 = msg[x].user.username


	
	if (type_room == "Private"):
		rooms = Room.objects.filter(room_type__contains=type_room, authorized_users__contains=f'{request.user.username},')
	elif (type_room == "Group"):
		rooms = Room.objects.filter(room_type__contains=type_room, authorized_users__contains=f'{request.user.username},')
	else:
		rooms = Room.objects.filter(room_type__contains=type_room)
	return render(request, 'chat/room.html', {'room': room, 'msg':msg,'rooms':rooms})

@login_required
def update_room(request, slug):
	room = get_object_or_404(Room, slug=slug)
	form = RoomForm(instance=room)
	auth_user = room.authorized_users.split(',')
	auth_user = ','.join(auth_user[1:])
	tmp = 'This name has already been used!'
	if(request.method == 'POST'):
		try:
			
			form = RoomForm(request.POST, request.FILES, instance=room)
			if(form.is_valid()):
				room = form.save(commit=False)
				temp = form.cleaned_data["name"]
				temp = re.sub(u'[!@#$%¨&*(:)+=-?\'\"]', '', temp)
				temp = temp.lower().strip().split(" ")
				temp = '_'.join(temp)
				room.slug = f'{request.user.id}_{temp}'
				form.cleaned_data["name_authorized"] = form.cleaned_data["name_authorized"].replace(",,",",")
				if (form.cleaned_data["name_authorized"] != "None"):
						temp = [f'{request.user.username},',form.cleaned_data["name_authorized"]]
						room.authorized_users = f'{temp[0]}{temp[1]},'
				room.save()
				return redirect('../../')
		except IntegrityError as e: 
			messages.warning(request, 'This name has already been used!')
            
	return render(request, 'chat/room_update.html', {'form': form, 'room' : room, "auth_user":auth_user})


@login_required
def delete_room(request, slug):
	Room.objects.get(slug=slug).delete()
	return redirect("../")





def postal(request):
	return render(request, 'chat/cartao_postal.html')

chat/templates/chat/base.html
{% extends 'main/base.html' %}

{% block title %}Chat App{% endblock %}

{% block content %}
<style>
  body{
    background: #20c997;

  }

body::-webkit-scrollbar-thumb {
    background-image: -webkit-linear-gradient(330deg, #d4fc79 0%, #96e6a1 100%);
    background-image: linear-gradient(120deg, #d4fc79 0%, #96e6a1 100%);
}


</style>  


{% block chat_content %}{% endblock %}

{% block scripts %}{% endblock %}

{% endblock %}

chat/templates/chat/room.html
{% extends 'chat/base.html' %}

{% block title %}{{room.name}}{% endblock %}

{% block nav_content %}
<style>
  .navbar{
    background: #0d664c;
  }
</style>
<h2 style="color: white; width: max-content">{{room.name}}</h2>
{% endblock %}

{% block chat_content %}

<style>

  #chat_box{
    width: 100%;
    height: 100%;
    padding: 2%;
    
    background: rgba(255, 255, 255, 0.9);
    border: 1px solid gray;
    border-radius: 0 10px 10px 0;
  }
  #chat_css{
    height: 95%;
    overflow-y: auto;
  }
  #chat_room .card {
    margin-bottom: 10px;  
    background: #d3dbd9;
    border: 0px;
  }





  .room {
  background: white;
  width: 50%;
  align-items: center;
  }
  .room_style:hover {
  background: #bfbfbd;
   color: black;
  }
  
  #chat{
    position: absolute;
    width: 98%;
    height: 90%;
    margin: 0.2%;
  }
  #chat_groups{
    position: relative;
    width: 20%;
    height: 100%;
    margin: 0.2% 0% 0% 1%;
    border-radius: 10px 0px 0px 10px;
    background: #0d7859;
    overflow-y: auto;
  }
  #chat_room{
    position: relative;
    width: 80%;
    height: 100%;
    margin: 0.2% 0 0 0;
    padding: 0;
  }
  #chat_groups div .card{
    width: 100%;
    border: 0;
    border-bottom: 0.5px solid rgba(0, 0, 0, 0.250);
    border-radius: 0;
    text-decoration: none;
    color: black;
    font-family: Arial, sans-serif;
    margin-bottom: 0px; 

  }

  .btn-group a{
    border: 0;
    border-radius: 0;
    background-color: #32a87d;
  }
  .btn-group a:hover{
    border-radius: 0;
    background-color: #258562;
  }



  /*SCROLL*/
  .scrollbar-dusty-grass::-webkit-scrollbar-track {
      -webkit-box-shadow: inset 0 0 6px rgba(0, 0, 0, 0.1);
      background-color: #F5F5F5;
      border-radius: 10px;
  }

  .scrollbar::-webkit-scrollbar {
      width: 5px;
      background-color: #F5F5F5;
  }

  .scrollbar::-webkit-scrollbar-thumb {
      -webkit-box-shadow: inset 0 0 6px rgba(0, 0, 0, 0.1);
      background-color: rgba(200, 200, 200, 1.0);
  }

  .scrollbar {
      scrollbar-color: #d4fc79 #F5F5F5;
  }

</style>
<div id='chat' class="row align-items-start">
  <div id='chat_groups' class="col scrollbar">
    
     

      
    <div class="row align-items-start">
      <div class="card text-center" style="padding: 0px 0 ">
          <div class="col">
            <div class="btn-group" role="group">
                        <a href="../private/{{room.slug}}" class="btn btn">Private Chats</a>
                        <a href="../group/{{room.slug}}" class="btn btn">Group Chats</a>
                        <a href="../public/{{room.slug}}" class="btn btn">Public Chats</a>
            </div>
          </div>
      </div>
                    
            {% for room in rooms %}
            <a href="{% url 'chat:room' slug=room.slug type_room=room.room_type %}" class="card" style="width: 100%;">
                <div class="row align-items-start">
                    <img src="../media/{{room.room_picture}}" style="width: 50px; height: 50px; margin: 0; padding: 0 0 0 5px;
                     margin: 4px 0 4px 0;border-radius: 100%;" alt="...">
                      <div class="card-body text-left  room fs-5" style="margin: 0; padding: 10px 0 0 10px; height: 40px; overflow-x: initial;overflow-y: hidden;"> {{room.name}}
                </div>
              </div>
            </a>

              <!--<a href="{% url 'chat:room' slug=room.slug type_room=room.room_type %}" class="card text-center room fs-4" >{{room.name}}</a>-->
            {% endfor %}
    </div>
  </div>
  <div id='chat_room'>

                      <div id="chat_box">

                        <div id="chat_css" class="scrollbar">
                            {% for message in msg %}
                            {% if message.user.username == request.user.username %}
                              <div class="card text-end">
                            {% else %}
                              {% if message.user.username|slice:"4:" == request.user.username%}
                                <div class="card text-end">
                              {% else %}
                              <div class="card">
                              {% endif %}
                             {% endif %}
                                <div class="card-body">
                                  {% if 'not' in message.user.username %} 
                                    {% else %}
                                    {% if message.user.first_name != '' %}
                                            <h5>{{message.user.first_name}}</h5>
                                      {% else %}
                                          <h5>{{message.user.username}}</h5>
                                    {% endif %}
                                   {% endif %}
                                    <p class="card-text">{{ message.content}}</p>
                                    <p class="card-text" style="position: absolute; bottom: 2%; right: 2%;">
                                    {% if message.date_added.minute < 10 %}
                                      {{ message.date_added.hour }}:0{{ message.date_added.minute }}
                                    {% else %}
                                      {{ message.date_added.hour }}:{{ message.date_added.minute }}
                                      {% endif %}

                                  </p>
                                </div>
                              </div>
                            {% endfor %}
                        </div>
                            <form method="POST" action=".">{% csrf_token %}
                              <div class="input-group">
                                  <input type="text" id="chat-message-input" class="form-control" name="content" placeholder="Your message">
                                  <button id="chat-message-submit" class="btn btn-secondary" >Send</button>
                              </div>
                            </form>
                      </div>



  </div>
</div>



{% block script %}
{{ room.slug|json_script:"json-roomname" }}
{{request.user.username|json_script:"json-username"}}

<script>
  const roomName = JSON.parse(document.getElementById('json-roomname').textContent);
  const userName = JSON.parse(document.getElementById('json-username').textContent);
  

  const charSocket = new WebSocket(
      (window.location.protocol === 'https:' ? 'wss' : 'ws') + '://'
      + window.location.host
      + '/ws/chat/'
      + roomName
      + '/'

    );
  charSocket.onmessage = function(e){
    console.log('onmessage')

    const data = JSON.parse(e.data);
    const user = document.querySelectorAll('.card h5')
    
    const date = new Date();
    const hour    = date.getHours();          // 0-23
    const min     = date.getMinutes(); 
    if (data.message){
      if (user.length != 0){
        let html = '<div class="card">'
        if (data.username == userName){ 
           html = '<div class="card text-end">'
         }
            html +=    '<div class="card-body">'
        if ((user[user.length - 1].textContent) == data.username){ 
          }
        else{
          html +=      '<h5>' + data.username + '</h5>'
        }
            html +=      '<p class="card-text">' + data.message + '</p>'
            html +=      '<p class="card-text" style="position: absolute; bottom: 2%; right: 2%;">' + hour + ':' + min + '</p>'
            html +=    '</div>'
            html +=  '</div>'
          document.querySelector('#chat_css').innerHTML += html
        
      }
      else{
        let html = '<div class="card">'
        if (data.username == userName){ 
           html = '<div class="card text-end">'
         }
              html +=    '<div class="card-body">'
              html +=      '<h5>' + data.username + '</h5>'
              html +=      '<p class="card-text">' + data.message + '</p>'
              html +=      '<p class="card-text" style="position: absolute; bottom: 2%; right: 2%;">' + hour + ':' + min + '</p>'
              html +=    '</div>'
              html +=  '</div>'
          document.querySelector('#chat_css').innerHTML += html
        
    }
    scrollToBottom();
  }
    else{
      alert('The message was empty!');
    }
  }

  charSocket.onclose = function(e){
    console.log('onclose')
  }



  //



  document.querySelector('#chat-message-submit').onclick = function(e){
    e.preventDefault();


    const messageInputDom = document.querySelector('#chat-message-input');
    const message = messageInputDom.value;

    charSocket.send(JSON.stringify({
      'message' : message,
      'username' : userName,
      'room' : roomName
    }));

    messageInputDom.value = '';

    return false;
  }

  //

window.onload = function () {
  scrollToBottom();
  $("div .form-group").addClass("form-floating mb-3");
    $("div .form-floating input").addClass("form-control");
    $("div .form-floating input").attr("placeholder", "RANDOM");
}
  function scrollToBottom(){
    const objDiv = document.querySelector('#chat_css');
    objDiv.scrollTop = objDiv.scrollHeight;
  }

//MEDIA QUERY "CSS" FUNCTIONS

if ((window.matchMedia("(min-width:1200px)").matches)) {
  /* a viewport tem pelo menos 1200 pixels de largura */
}else if((window.matchMedia("(min-width:1000px)").matches)){
    temp = document.querySelectorAll("#chat_groups .card-body")
    console.log(temp)
    //document.querySelector("#chat_groups .card-body")
    var index = 0, length = temp.length;
  for ( ; index < length; index++) {
      temp[index].classList.add('fs-6');
      temp[index].classList.remove('fs-5');
      temp[index].style.height = '30px';
  }
    
}else{
  document.querySelector("#chat_groups").style.display = "none";
  document.querySelector("#chat_room").style.width = "100%";
  document.querySelector("#chat_box").style.borderRadius = "10px";
}

</script>


{% endblock %}


{% endblock %}

chat/templates/chat/room_update.html
{% extends 'chat/base.html' %}

{% block title %}{{room.name}}{% endblock %}

{% block nav_content %}
<style>
  .navbar{
    background: #0d664c;
  }
</style>
<h2 style="color: white; width: max-content">{{room.name}}</h2>

{% endblock %}


{% block chat_content %}
{% load i18n %}
<style>
.room {
  background: #19b085;
  width: 30%;
  margin: 0 0.5%;
}
.room:hover {
  background: #0e7558;
}
.card{
  width: 100%;
  height: 140px;
}


</style>

<div class="container">
  <div class="row align-items-start">
    <div class="col" style="margin: 5px;">
      <div class="card text-center" style="height: 100%;">
        <div class="card-body">


                {% if messages %}
                  {% for message in messages %}
                  {% if tmp in message|stringformat:"s" %}
                    <div class="alert alert-danger">
                      <strong>{{message}}</strong>
                    </div>
                    {% endif %}
                 {% endfor %}
                {% endif %}


          <h1 class="card-title" >Update your Room</h1>
          <form method="POST" id="form_room" enctype="multipart/form-data">{% csrf_token %}
            
            <div class="input-group mb-3">
              <label class="input-group-text" for="inputGroupFile01">Room Picture</label>
              <input type="file" name="room_picture" id="id_room_picture" class="form-control">
          </div>
            <div class="form-floating mb-3">
              {{form.name}}
              <label for="floatingInput">Name</label>
            </div>
            <div class="input-group mb-3">
              <label class="input-group-text" for="id_room_type">Options</label>
              {{form.room_type}}
            </div>
            <div id="div_auth" class="form-floating mb-3" style="display : none;">
              {{form.name_authorized}}
              <label id="lb_auth" for="floatingInput"></label>
            </div>
            <input type="hidden" name="authorized_users" cols="40" rows="10" maxlength="10000" required="" id="id_authorized_users" value={{request.user}},></input>
            <input type="hidden" name="slug" maxlength="50" required="" id="id_slug" value=NoSLUG{{request.user}}>
            <button type="submit" class="btn btn-success" style="margin: 4%;" value="Save">Update</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  window.onload = function () {
    $("div .form-group").addClass("form-floating mb-3");
    $("div .form-floating input").addClass("form-control").attr("placeholder", "RANDOM");
    $("#id_room_type").addClass("form-select");
    $("#id_room_type option:first-child").text("Select type room").attr('selected', 'selected');
    $("#id_slug").attr("type", "hidden");
}

document.querySelector('#id_room_type').onchange = function(e){
    let select = document.querySelector("#id_room_type")
    let option = select.options[select.selectedIndex].text
    var field = document.getElementById('div_auth')
    if (option == "Private"){
      field.style.display = "block";
      $("#id_name_authorized").attr("value", "{{auth_user}}");
      $("#id_name_authorized").attr("maxlength", 40);
      $("#lb_auth").text("Add the user (only one) what you want create the private chat");
    }
    else if (option == "Group"){
      field.style.display = "block";
      $("#id_name_authorized").attr("value", "{{auth_user}}");
      $("#id_name_authorized").attr("maxlength", 10000);
      $("#lb_auth").text("Add the users what you want add to your group chat");
    }else{
      field.style.display =  "none";
      $("#id_name_authorized").attr("value", "None");
    }

    return false;
  }

    
</script>
{% endblock %}

chat/templates/chat/rooms.html
{% extends 'chat/base.html' %}

{% block title %}{{type_room}} Rooms{% endblock %}

{% block nav_content %}
<style>
  .navbar{
    background: #0d664c;
  }
</style>
<h2 style="color: white; width: max-content">{{type_room}} Rooms</h2>

{% endblock %}


{% block chat_content %}
{% load i18n %}
{% load custom_filter %}
<style>
.room {
  background: #19b085;
  width: 30%;
  margin: 0 0.5%;
}
.room:hover {
  background: #0e7558;
}
.card{
  width: 100%;
  height: 140px;
}
#postal_card{
    display: ;
    justify-content: center;
    transform-style: preserve-3d;
    transition: all .5s;
    /*margin-top: 50px;*/
}


</style>

<div class="container">
  <div class="row align-items-start">
    <div class="col" style="margin: 5px;">
      <div class="card text-center" style="height: 100%;">
        <div class="card-body">


                {% if messages %}
                  {% for message in messages %}
                  {% if tmp in message|stringformat:"s" %}
                    <div class="alert alert-danger">
                      <strong>{{message}}</strong>
                    </div>
                    {% endif %}
                 {% endfor %}
                {% endif %}

          <div class="row align-items-start alig_cards">
            <div id="css_col" class="col" style="margin: 5px; border-right: 1px solid black;">
                  <h1 class="card-title" >Register a Room</h1>
                  <form method="POST" id="form_room" enctype="multipart/form-data">{% csrf_token %}

                    <div class="form-floating mb-3">
                      {{form.name}}
                      <label for="floatingInput">Name</label>
                    </div>
                    <div class="input-group mb-3">
                       <label class="input-group-text" for="inputGroupFile01">Room Picture</label>
                       <input type="file" name="room_picture" id="id_room_picture" class="form-control">
                    </div>
                    <div class="input-group mb-3">
                      <label class="input-group-text" for="id_room_type">Options</label>
                      {{form.room_type}}
                    </div>
                    <div id="div_auth" class="form-floating mb-3" style="display : none;">
                      {{form.name_authorized}}
                      <label for="floatingInput">Add the user (only one) what you want create the private chat</label>
                    </div>


                    <input type="hidden" name="authorized_users" cols="40" rows="10" maxlength="10000" required="" id="id_authorized_users" value={{request.user}},></input>
                    <input type="hidden" name="slug" maxlength="50" required="" id="id_slug" value=NoSLUG{{request.user}}>
                    <button type="submit" class="btn btn-success" style="margin: 4%;" value="Save">Register</button>
                  </form>
            </div>
          
            <div class="col" style="margin: 5px;">
              <h1 class="card-title" >Search the Room</h1>
                    <div class="form-floating mb-3">
                      <input type="text" name="src_rooms" maxlength="40" required="" id="id_src_rooms"></input>
                      <label for="floatingInput">Name</label>
                    </div>
            </div>
          </div>
        </div>
      </div>
    </div>



    <div id="rooms_cards">

      <div class="row align-items-start alig_cards">
      {% load room_custom_filter %}
          {% for room in rooms %}
                {% if forloop.counter|card_order %}
                    </div>
                    <div class="row align-items-start alig_cards">
              {% endif %}
                  
                <div  id={{room.id}} class="col initial_card" style="margin: 5px;" >
                  <div id={{room.slug|lower}} class="card text-center">
                    <div class="card-body">
                      <div id="front" style="overflow-y: hidden;margin-top: 20px; height: 60px; margin-bottom: 15px;">
                      <h1 class="card-title">
                        <button  class="btn btn-primary" onmouseover="flipFunc(event,'front')" style="border-radius:100%">...</button>
                        <img  src="media/{{room.room_picture}}" style="width: 50px; height: 50px; margin: 0; padding: 0 0 0 5px;margin: 4px 0 4px 0;border-radius: 100%; left: 0;" alt="...">
                      {{room.name}}
                      
                    </h1>
                      </div>
                      <div id="back" class="row align-items-center" style="display: none; padding: 20px 0 0 0;">
                        <div class="col">
                          <button  class="btn btn-primary" onmouseover="flipFunc(event,'back')" style="border-radius:100%">...</button>
                          <input type="hidden" name="slug" maxlength="50" required="" id="id_slug" value=room.slug>
                          {% if request.user.id|canEditRoom:room.slug %}
                            <a href="{% url 'chat:update_room' room.slug %}" class="btn btn-warning">Alter</a>
                          {% endif %}
                          <a href="{% url 'chat:room' room.slug %}" class="btn room">Join</a>
                          {% if request.user.id|canEditRoom:room.slug %}
                            <a href="{% url 'chat:delete_room' room.slug %}" class="btn btn-danger">Delete</a>
                          {% endif %}
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
          {% endfor %}
    </div>
  </div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js" type="text/javascript"></script>
<script>
  window.onload = function () {
    $("div .form-group").addClass("form-floating mb-3");
    $("div .form-floating input").addClass("form-control").attr("placeholder", "RANDOM");
    $("#id_room_type").addClass("form-select");
    $("#id_room_type option:first-child").text("Select type room").attr('selected', 'selected');
}


//
function flipFunc(e, type){
    try {
      var element = e.srcElement
      element = element.parentNode.parentNode.parentNode.parentNode.parentNode.id.toString()
    } catch {
      var element = e.path[5].id.toString()
    }
  front = $("#"+element+" #front")
  back = $("#"+element+" #back")
  if (front.css("display") == "block" && type == "front"){
    back.css("display","block");
    front.css("display","none");
  }else{
  back.css("display","none");
  front.css("display","block");
  
  }
        
}


// SETTINGS FOR SHOW FIELD OF USERS ALLOWED - SELECT OPTION
document.querySelector('#id_room_type').onchange = function(e){
    let select = document.querySelector("#id_room_type")
    let option = select.options[select.selectedIndex].text
    var field = document.getElementById('div_auth')
    if (option == "Private"){
      field.style.display = "block";
      $("#id_name_authorized").attr("value", "");
    }else{
      field.style.display =  "none";
      $("#id_name_authorized").attr("value", "None");
    }

    return false;
  }

  //



// SEARCH ROOMS - FILTER
document.querySelector('#id_src_rooms').onkeyup = function(e){
    let input_src = document.querySelector("#id_src_rooms").value
    let temp = document.querySelectorAll("#rooms_cards div .initial_card");
    var index = 0, length = temp.length;
    if (input_src == ""){
      for ( ; index < length; index++) {
        temp[index].style.display =  "block";
      }

    }
    else{
      for ( ; index < length; index++) {
          temp[index].style.display =  "none";
      }
      input_src = input_src.toLowerCase().replace(/ /g, "_");
      /*temp = document.querySelectorAll("#rooms_cards div[id*="+input_src+"]")*/
      index = 0, length = temp.length;
      for ( ; index < length; index++) {
        if(temp[index].querySelector("div[id*="+input_src+"]") != null){
            temp[index].style.display =  "block";
        }
      }
    }
}




//MEDIA QUERY "CSS" FUNCTIONS

if (window.matchMedia("(min-width:770px)").matches) {
  /* a viewport tem pelo menos 800 pixels de largura */
} else if((window.matchMedia("(min-width:600px)").matches)){
    /* a viewport menos que 800 pixels de largura */
  let temp = document.querySelectorAll(".alig_cards")//.classList.remove('row');
  var index = 0, length = temp.length;
  for ( ; index < length; index++) {
      temp[index].classList.remove('row');
  }
  temp = document.querySelector("#css_col")
  temp.style.borderRight = "0";
  temp.style.borderBottom  = "1px solid black";
  temp.style.marginBottom  = "30px"
}
else{
  /* a viewport menos que 800 pixels de largura */
  let temp = document.querySelectorAll(".alig_cards")//.classList.remove('row');
  var index = 0, length = temp.length;
  for ( ; index < length; index++) {
      temp[index].classList.remove('row');
  }
  temp = document.querySelector("#css_col")
  temp.style.borderRight = "0";
  temp.style.borderBottom  = "1px solid black";
  temp.style.marginBottom  = "30px";


  $("#back button").attr("onmouseover","")
  $("#back button").attr("onclick","flipFunc(event,'back')")
  $("#front button").attr("onmouseover","")
  $("#front button").attr("onclick","flipFunc(event,'front')")



}
</script>
{% endblock %}