automail/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = 'automail'
urlpatterns = [
    path('', index,  name='email_view'),
    path('view_email/<int:id>', view_email,  name='base_temp'),
    path('view_email/', view_email, kwargs={"id":"default"}, name='base_temp'),
    path('delete/<int:id>', delete_email,  name='delete_email'),
]

chat/urls.py
from django.urls import path
from .views import *
#from chat import urls
from django.conf import settings
from django.conf.urls.static import static

app_name = 'chat'
urlpatterns = [
    path('', rooms, kwargs={'type_room':"Private"},  name='private_rooms'),
    path('public', rooms, kwargs={'type_room':"Public"},  name='public_rooms'),
    path('group', rooms, kwargs={'type_room':"Group"},  name='group_rooms'),
    path('private/<slug:slug>', room, kwargs={'type_room':"Private"}, name='room'),
    path('public/<slug:slug>', room, kwargs={'type_room':"Public"}, name='room'),
    path('group/<slug:slug>', room, kwargs={'type_room':"Group"}, name='room'),
    path('update/<slug:slug>', update_room,  name='update_room'),
    path('delete/<slug:slug>', delete_room,  name='delete_room'),



    path('postal', postal,  name='postal'),
] 

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

myProject/urls.py
from django.contrib import admin
from django.urls import path, include
#from chat import urls


urlpatterns = [
    path('', include('main.urls')),
    path('accounts/', include('user_auth.urls')), #google authentication
    path('', include('django.contrib.auth.urls')),#"local" authentication
    path('chat/', include('chat.urls', namespace='chat')), # chat application
    path('automail/', include('automail.urls', namespace='email')), # email application
    path('chess/', include('chess.urls', namespace='chess')), # chess application
    path('admin/', admin.site.urls),
]

automail/models.py
from django.db import models
from django.contrib.auth.models import User
import django.utils.timezone

# Create your models here.
class Automail(models.Model):
	user = models.ForeignKey(User, related_name='automail', on_delete=models.CASCADE)
	to_email = models.EmailField(max_length=254)
	subject = models.CharField(max_length=50)
	content = models.TextField()
	date_added = models.DateTimeField(default=django.utils.timezone.now)

	def __str__(self):
		day = self.date_added.day
		month = self.date_added.month
		if (day < 10):
			day = '0'+ str(day)
		if (month < 10):
			month = '0'+ str(month)
		return f'{self.user.username} - {self.subject} | {day}-{month}-{self.date_added.year}'

automail/forms.py
from django import forms
from .models import Automail

class AutomailForm(forms.ModelForm):
	password = forms.CharField(max_length=50)
	save_or_submit = forms.CharField(max_length=7)
	class Meta:
		model = Automail
		fields = [
		'user',
		'to_email',
		'subject',
		'content']

automail/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
# Create your views here.
from .models import Automail
from user_auth.models import Account
from .forms import AutomailForm
from .functions import  sendEmailPostCard
from .mail_templates import mail_templates_base


@login_required
def index(request):
	mails = Automail.objects.filter(user__id__contains=request.user.id)
	return render(request, 'automail/index.html', {'mails':mails})

@login_required
def delete_email(request, id):
	Automail.objects.get(id=id).delete()
	return redirect("../")
	
@login_required
def view_email(request, id):
	try:
		email = Automail.objects.get(user__id__contains=request.user.id, id=id)
		form = AutomailForm(instance=email)
	except:
		form = AutomailForm()
		email = False
	try:
		user_account = Account.objects.get(user=request.user.id)
		auto_password = user_account.auto_password
		config_mail = user_account.config_mail
	except:
		auto_password = "Query DoesNotExist"
		config_mail = "Query DoesNotExist"

	if(request.method == 'POST'):
		try:
			form = AutomailForm(request.POST, instance=email)
		except:
			form = AutomailForm(request.POST)
		if(form.is_valid()):
				emailData = {'from_email':request.user.email,'to_email':form.cleaned_data["to_email"]
				,'subject':form.cleaned_data["subject"],'content':form.cleaned_data["content"]}
				passw = form.cleaned_data["password"]
				save_or_subm = form.cleaned_data["save_or_submit"]
				form.save()
				if (save_or_subm == "submit"):
					if (auto_password == "Query DoesNotExist"):
						send_email = sendEmailPostCard(emailData)
					elif (auto_password == True):
						send_email = sendEmailPostCard(emailData,user_account.smtp_server,user_account.port_server,user_account.host_user,
									user_account.host_password,user_account.require_tls, user_account.config_mail)
					else:
						send_email = sendEmailPostCard(emailData,user_account.smtp_server,user_account.port_server,user_account.host_user,
									passw,user_account.require_tls, user_account.config_mail)
					if (send_email == "SUCESSFULL"):
						print()
						return render(request, 'automail/success_email.html', {})
					else:
						print()
						return render(request, 'automail/email_error.html', {})
				return redirect('../')

	base,template = mail_templates_base(type)
	return render(request, 'automail/create_mail.html', {'base':base,'template':template,'form':form, 'email':email, "auto_password":auto_password, "config_mail":config_mail})

automail/templates/automail/base.html
<!DOCTYPE html>
<html>
<head>
<title>Page Title</title>
    <meta charset="utf-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'email_sidebar.css' %}" >
    <link rel="stylesheet" type="text/css" href="{% static 'email.css' %}" >





</head>
<body>

{% block before_wrapper %}{% endblock %}
<div id="wrapper" style="height: 100%;">

    <!--SideBar -->

    <div id="sidebar-wrapper">

        <div class="sidebar-nav" >

            <!-- SIDE BAR ITENS FOR INSERT CONTENT -->
            {% block side_opt %}{% endblock %}
            <div class="side_items mail_opts">
                    {% if not user.is_authenticated %}
                        <h1 class='title-sidebar'>Welcome</h1>
                        <h1 class='title-sidebar'>To my site</h1>
                        {% else %}
                            <h1 class='title-sidebar'>Welcome</h1>
                            
                            {% if user.first_name != '' %}
                                 {% if user.first_name|length < 13 %}
                                <h1 class='title-sidebar'>{{user.first_name}}</h1>
                                {% else %}
                                <h1 class='title-sidebar'>{{user}}</h1>
                                {% endif %}
                            {% else %}
                                    <h1 class='title-sidebar'>{{user}}</h1>
                            {% endif %}
                        {% endif %}
                <a href="/" class='btn'>HomePage</a>
                <a href="/admin" class='btn'>Admin</a>
                {% block main_menu_opt %}
                {% endblock %}
                <a href="/accounts/change_record" class='btn text-start'>Record</a>
                
                <a href="/accounts/logout" id='a_logout' class='btn' >Logout</a>
                
            </div>
        </div>
    </div>

     <!--Contents -->
    
<div id="page-content-wrapper">

        {% block nav_content %}{% endblock %}                 

     
    <div id="side_menu_widgets">

            <!-- Options side bar -->
                <!-- <button id="text_opt" class="opt menu-toggle" onclick="showopt('mail_menu')"></button> -->
                <button id="menu_opt" class="opt menu-toggle" onclick="showopt('mail_opts')"></button>

                
                {% block side_buttons %}{% endblock %}
    </div>


        <div style="padding-left: 90px;">
            {% block content_view %}{% endblock %}
        </div>

    

</div>


</div>





<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js" type="text/javascript"></script>
<script type="text/javascript" src="{% static 'email.js' %}"></script>
{% block scripts %}{% endblock %}
</body>
</html>

automail/templates/automail/email_error.html
<!DOCTYPE html>
<html>
<head>
<title>Page Title</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    


{% load i18n %}
<style>
    
    .row div{
    background: red;
    padding: 50px;
    /*Style glass*/
    border-radius: 10px;
    background: rgba(255, 0, 0, 0.350);
    border: 1px solid #fff;
    backdrop-filter:  blur(3px);
    box-shadow: 0 0 100px 0 rgba(29, 29, 29, 0.503);
    }

</style>

</head>
<body>


    <div class="row">
  <div class="col-md-5 mx-auto" style="margin-top: 30vh; padding: 8vh;">

        <h1>{% translate "Template cadastrado, mas não enviado. Falha na comunicação com o servidor, após 3 tentativas foi atingido o tempo limite. Tente enviar novamente" %}</h1>
        <a href="../" class="btn btn-primary">MENU INICIAL</a>

</div>
</div>








</body>
</html>

automail/templates/automail/index.html
{% extends 'automail/base.html' %}
{% block nav_content %}{% endblock %}
{% block main_menu_opt %}
<a href="/automail/view_email/" class='btn'>Create/View Email</a>
{% endblock %}
{% block side_opt %}{% endblock %}
{% block side_buttons %}{% endblock %}
{% block content_view %}



<style>
.email {
  background: #19b085;
  width: 30%;
  margin: 0 0.5%;
}
.email:hover {
  background: #0e7558;
}
.card{
  width: 100%;
  height: 140px;
}


</style>

<div class="container">
  <div class="row align-items-start">
    <div class="col" style="margin: 5px;">
      <div class="card text-center" style="height: 100%;">
        <div class="card-body">        
              <h1 class="card-title" >Search Email</h1>
                    <div class="form-floating mb-3">
                      <input type="text" name="src_emails" maxlength="40" required="" id="id_src_emails">
                      <label for="floatingInput">Name</label>
                    </div>
        </div>
      </div>
    </div>



          
    <div id="emails_cards">

      <div class="row align-items-start alig_cards">
      {% load custom_filter %}
          {% for mail in mails %}
                {% if forloop.counter|mail_order %}
                    </div>
                    <div class="row align-items-start alig_cards">
              {% endif %}
                  
                <div id={{mail.id}} class="col initial_card" style="margin: 5px;">
                  <div id={{mail.subject|lower}} class="card text-center">
                    <div class="card-body">
                      <div id="front" style="overflow-y: hidden;margin-top: 20px; height: 60px; margin-bottom: 15px;">
                      <h1 class="card-title" >
                      <button  class="btn btn-primary" onmouseover="flipFunc(event,'front')" style="border-radius:100%">...</button>
                      {{mail.subject}} - {{mail.date_added|dateFormating}} 
                      </div>
                     <div id="back" class="row align-items-center" style="display: none; padding: 20px 0 0 0;">
                        <div class="col">
                          <button  class="btn btn-primary" onmouseover="flipFunc(event,'back')" style="border-radius:100%">...</button>
                          <!-- <a href="" class="btn btn-warning">Alter</a> -->
                          <a href="{% url 'automail:base_temp' mail.id %}" class="btn email" style="color:white;">Send or Alter</a>
                           <a href="{% url 'automail:delete_email' mail.id %}" class="btn btn-danger">Delete</a>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
    
          {% endfor %}







    </div>
  </div>
</div>

{% endblock %}


{% block scripts %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js" type="text/javascript"></script>
<script>
  window.onload = function () {
    $("div .form-group").addClass("form-floating mb-3");
    $("div .form-floating input").addClass("form-control").attr("placeholder", "RANDOM");
    $("#id_email_type").addClass("form-select");
}
//
function flipFunc(e, type){
    try {
      var element = e.srcElement
      element = element.parentNode.parentNode.parentNode.parentNode.parentNode.id.toString()
    } catch {
      var element = e.path[5].id.toString()
    }
  front = $("#"+element+" #front")
  back = $("#"+element+" #back")
  if (front.css("display") == "block" && type == "front"){
    back.css("display","block");
    front.css("display","none");
  }else{
  back.css("display","none");
  front.css("display","block");
  
  }
        
}

//

  //



// SEARCH emailS - FILTER
document.querySelector('#id_src_emails').onkeyup = function(e){
    let input_src = document.querySelector("#id_src_emails").value
    let temp = document.querySelectorAll("#emails_cards div .initial_card");
    var index = 0, length = temp.length;
    if (input_src == ""){
      for ( ; index < length; index++) {
        temp[index].style.display =  "block";
      }

    }
    else{
      for ( ; index < length; index++) {
          temp[index].style.display =  "none";
      }
      input_src = input_src.toLowerCase().replace(/ /g, "_");
      /*temp = document.querySelectorAll("#emails_cards div[id*="+input_src+"]")*/
      index = 0, length = temp.length;
      for ( ; index < length; index++) {
        if(temp[index].querySelector("div[id*="+input_src+"]") != null){
            temp[index].style.display =  "block";
        }
      }
    }
}




//MEDIA QUERY "CSS" FUNCTIONS

if (window.matchMedia("(min-width:770px)").matches) {
  /* a viewport tem pelo menos 800 pixels de largura */
} 
else if((window.matchMedia("(min-width:600px)").matches)){
    /* a viewport menos que 800 pixels de largura */
  let temp = document.querySelectorAll(".alig_cards")//.classList.remove('row');
  var index = 0, length = temp.length;
  for ( ; index < length; index++) {
      temp[index].classList.remove('row');
  }
  temp = document.querySelector("#css_col")
  temp.style.borderRight = "0";
  temp.style.borderBottom  = "1px solid black";
  temp.style.marginBottom  = "30px"
}
else{
  /* a viewport menos que 800 pixels de largura */
  let temp = document.querySelectorAll(".alig_cards")//.classList.remove('row');
  var index = 0, length = temp.length;
  for ( ; index < length; index++) {
      temp[index].classList.remove('row');
  }
  temp = document.querySelector("#css_col")
  temp.style.borderRight = "0";
  temp.style.borderBottom  = "1px solid black";
  temp.style.marginBottom  = "30px";


  $("#back button").attr("onmouseover","")
  $("#back button").attr("onclick","flipFunc(event,'back')")
  $("#front button").attr("onmouseover","")
  $("#front button").attr("onclick","flipFunc(event,'front')")



}
</script>


{% endblock %}

automail/templates/automail/noAccessible.html
<!DOCTYPE html>
<html>
<head>
<title>Page Title</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    


{% load i18n %}
<style>
    
    .row div{
    background: red;
    padding: 50px;
    /*Style glass*/
    border-radius: 10px;
    background: rgba(255, 0, 0, 0.350);
    border: 1px solid #fff;
    backdrop-filter:  blur(3px);
    box-shadow: 0 0 100px 0 rgba(29, 29, 29, 0.503);
    }

</style>

</head>
<body>


    <div class="row">
  <div class="col-md-5 mx-auto" style="margin-top: 30vh; padding: 8vh;">

        <h1>{% translate "O Item que você está buscando não existe, ou não há permissão para acessa-lo" %}</h1>

</div>
</div>








</body>
</html>

automail/templates/automail/success_email.html
<!DOCTYPE html>
<html>
<head>
<title>Page Title</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    


{% load i18n %}
<style>
    
    .row div{
    background: red;
    padding: 50px;
    /*Style glass*/
    border-radius: 10px;
    background: rgba(255, 0, 0, 0.350);
    border: 1px solid #fff;
    backdrop-filter:  blur(3px);
    box-shadow: 0 0 100px 0 rgba(29, 29, 29, 0.503);
    }

</style>

</head>
<body>


    <div class="row">
  <div class="col-md-5 mx-auto" style="margin-top: 30vh; padding: 8vh;">

        <h1>{% translate "Template Cadastrado e e-mail enviado com sucesso, Verifique o Spam" %}</h1>
        <a href="../" class="btn btn-primary">MENU INICIAL</a>
</div>
</div>








</body>
</html>