chat/urls.py
from django.urls import path
from .views import *
#from chat import urls
from django.conf import settings
from django.conf.urls.static import static

app_name = 'chat'
urlpatterns = [
    path('', rooms, kwargs={'type_room':"Private"},  name='private_rooms'),
    path('public', rooms, kwargs={'type_room':"Public"},  name='public_rooms'),
    path('group', rooms, kwargs={'type_room':"Group"},  name='group_rooms'),
    path('private/<slug:slug>', room, kwargs={'type_room':"Private"}, name='room'),
    path('public/<slug:slug>', room, kwargs={'type_room':"Public"}, name='room'),
    path('group/<slug:slug>', room, kwargs={'type_room':"Group"}, name='room'),
    path('update/<slug:slug>', update_room,  name='update_room'),
    path('delete/<slug:slug>', delete_room,  name='delete_room'),



    path('postal', postal,  name='postal'),
] 

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

myProject/urls.py
from django.contrib import admin
from django.urls import path, include
#from chat import urls


urlpatterns = [
    path('', include('main.urls')),
    path('accounts/', include('user_auth.urls')), #google authentication
    path('', include('django.contrib.auth.urls')),#"local" authentication
    path('chat/', include('chat.urls', namespace='chat')), # chat application
    path('automail/', include('automail.urls', namespace='email')), # email application
    path('chess/', include('chess.urls', namespace='chess')), # chess application
    path('admin/', admin.site.urls),
]

user_auth/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, include
from .views import *



urlpatterns = [
path('', include('allauth.urls')), #google authentication
path('password_reset/', auth_views.PasswordResetView.as_view(html_email_template_name='registration/password_reset_email.html'),name='password_reset'),
path('register/', register, name='register'), #"local" authentication
path('change_record/', register_change, name='change-record'), #"local" authentication
]

user_auth/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Account(models.Model):
	CONFIG_CHOICES = (
        ("configure", "Configure Send by my e-mail"),
        ("forward", "Forward to my email")
    )

	user = models.OneToOneField(User, on_delete=models.CASCADE)
	config_mail = models.TextField(max_length=100, choices=CONFIG_CHOICES, blank=True, null=True)
	smtp_server = models.CharField(max_length=100, blank=True, null=True)
	smtp_server = models.CharField(max_length=100, blank=True, null=True)
	port_server = models.CharField(max_length=100, blank=True, null=True)
	host_user = models.CharField(max_length=100, blank=True, null=True)
	host_password = models.CharField(max_length=100, blank=True, null=True)
	auto_password = models.BooleanField(blank=True, null=True)
	require_tls = models.BooleanField(blank=True, null=True)

	def __str__(self):
		return self.user.username

user_auth/forms.py
from django import forms
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from .models import Account
# Create your forms here.
class RegisterForm(UserCreationForm):
	email = forms.EmailField()
	class Meta:
		model = User
		fields = [
		'username',
		'email',
		'password1',
		'password2'
		]
		unlabelled_fields = ('username', 'email','password1',
		'password2')

class RegisterChangeForm(UserChangeForm):
	email = forms.EmailField()
	class Meta:
		model = User
		fields = [
		'first_name',
		'last_name',
		'email'
		]

class AccountChangeForm(forms.ModelForm):
	class Meta:
		model = Account
		fields = '__all__'
	
		

user_auth/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm, RegisterChangeForm, AccountChangeForm
from .models import Account
# Create your views here.
def register(response):
	form = RegisterForm()
	if response.method == "POST":
		form = RegisterForm(response.POST)
		if form.is_valid():
			form.save()
			return redirect("../../")
	context = {
		'form' : form
	}
	return render(response, 'user_auth/register.html', context)

def register_change(response):
	user = response.user
	form = RegisterChangeForm(initial={'first_name': user.first_name,
										'last_name': user.last_name,
										'email': user.email})
	try:
		user_account = Account.objects.get(user=user.id)
		account_form = AccountChangeForm(initial={'user' : user.id,
												'config_mail':user_account.config_mail,
												'smtp_server':user_account.smtp_server,
												'port_server':user_account.port_server,
												'host_user':user_account.host_user,
												'host_password':user_account.host_password,
												'auto_password':user_account.auto_password,
												'require_tls':user_account.require_tls})
	except Exception as e: 
		#'Account matching query does not exist.'
			account_form = AccountChangeForm()
		


	if response.method == "POST":
		form = RegisterChangeForm(response.POST, instance=response.user)
		try:
			account_form = AccountChangeForm(response.POST, instance=user_account)
		except Exception as e:
			#"local variable 'user_account' referenced before assignment"
				account_form = AccountChangeForm(response.POST)
		if form.is_valid():
			account = account_form.save(commit=False)
			passw = account_form.cleaned_data["host_password"]
			if (passw == None or passw == "" or passw == False):
				account.auto_password = False
			else:
				account.auto_password = True
			passw = account_form.cleaned_data["config_mail"]
			if (passw == "forward"):
				account.auto_password = True
			elif (passw == "" or passw == None):
				account.config_mail = "forward"
			form.save()
			account_form.save()
			return redirect("../../")
	
	context = {
		'form' : form,
		'account_form' : account_form
	}
	return render(response, 'user_auth/register_complement.html', context)

user_auth/templates/user_auth/register.html
{% extends 'main/base.html' %}

{% block title %}Create an Account{% endblock %}
{% block content %}
{% load static %}
{% load i18n %}
<link rel="stylesheet" type="text/css" href="{% static 'style_form.css' %}" >
<!--import Bootstrap in yor main file-->

<style>
#form_css{
    padding: 5%;
    margin: 8% 4%;
  }
.errornote{
  color: white;
 }
.errorlist{
	color: white;
}
.row{
  width: 100%;
 }
</style>
<div class="row">
	<div class="col-md-8 mx-auto">
		<form method="POST" class=""> {% csrf_token %}
			<div id="form_css">
				<h1 id="title_reg">REGISTER YOUR USER</h1>
				<div class="form-floating mb-3">
					{{ form.username}}
					<label for="floatingInput">Username</label>
				</div>
				<div class="form-floating mb-3">
					{{ form.email}}
					<label for="floatingInput">Email</label>
				</div>
				<div class="form-floating mb-3">
					{{ form.password1}}
					<label for="floatingInput">Password</label>
				</div>
				<div class="form-floating mb-3">
					{{ form.password2}}
					<label for="floatingInput">Password confirmation</label>
				</div>
				{% if form.errors and not form.non_field_errors %}
		        <p class="errornote">
		        {% if form.errors.items|length == 1 %}
		        {% translate "Please correct the error below." %}
		        {{form.errors.items}}
		        {% else %}
		        {% translate "Please correct the errors below." %}
		        {% for x in form.errors.items %}
		        <p class="errornote">
		        {{x.1}}
		        </p>
		        {% endfor %}
		        {% endif %}
		        </p>
		        {% endif %}
				<div style="color: white;">
        <button type="submit" class="btn btn-success" style="width: 30%; margin-right: 10px;" value="Save">Register</button>
        Already have an account? Then please <a href="/accounts/login/" style="color: skyblue;">Sign In</a>.</div>
			</div>
		</form>
	</div>
</div>

<script>
	window.onload = function () {
		$("div .form-group").addClass("form-floating mb-3");
		$("div .form-floating input").addClass("form-control");
		$("div .form-floating input").attr("placeholder", "RANDOM");
}

    
</script>
{% endblock %}

user_auth/templates/user_auth/register_complement.html
{% extends 'main/base.html' %}

{% block title %}Create an Account{% endblock %}
{% block content %}
{% load static %}
{% load i18n %}
<link rel="stylesheet" type="text/css" href="{% static 'style_form.css' %}" >
<!--import Bootstrap in yor main file-->

<style>
#form_css{
    padding: 5%;
    margin: 10% 10%;
  }
  .row{
  width: 100%;
 }
</style>
<div class="row">
	<div class="col-md-8 mx-auto">
		<form id="reg_comp" method="POST" class=""> {% csrf_token %}
			<div id="form_css">
				<h1 id="title_reg">UPDATE YOUR RECORD</h1>
				<div class="form-floating mb-3">
					{{ form.first_name}}
					<label for="floatingInput">First Name</label>
				</div>
				<div class="form-floating mb-3">
					{{ form.last_name}}
					<label for="floatingInput">Last Name</label>
				</div>
				<div class="form-floating mb-3">
					{{ form.email}}
					<label for="floatingInput">Email</label>
				</div>
				{{account_form.user}}
				<div style="margin-bottom: 20px;">
				{{account_form.config_mail}}
				</div>
					<div>
					<select id="providers" name="mails" class="form-select" style="margin-right:10px; margin-bottom: 20px;">
						<option value="none" selected>Select Your Mail Provider</option>
	                    <option value="gmail">Gmail</option>
	                    <option value="outlook">Outlook / Hotmail / Live.com </option>
	                    <option value="msn">MSN</option>
	                    <option value="yahoo">Yahoo</option>
	                    <option value="locaweb">LocaWeb</option>
	                    <option value="expressoMG">Expresso MG</option>
	                    <option value="another">Another Provider</option>
	                </select>
           		</div>
				<div class="form-floating mb-3">
					{{account_form.smtp_server}}
					<label for="floatingInput">Smtp Server</label>
				</div>
				<div class="form-floating mb-3">
					{{account_form.port_server}}
					<label for="floatingInput">Port Smtp</label>
				</div>
				<div class="form-floating mb-3">
					{{account_form.host_user}}
					<label for="floatingInput">Host User</label>
				</div>
				<div class="form-floating mb-3">
					{{account_form.host_password}}
					<label for="floatingInput">Set the password if you don't want to enter it with every email send</label>
				</div>
					{{account_form.auto_password}}
				<div>
					{{account_form.require_tls}}
				</div>
				
				<div style="color: white;">
        
			</div>
			<button class="btn btn-success" style="width: 30%; margin-right: 10px;" onclick="catch_provider(event)">Change</button>
		</form>

	</div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js" type="text/javascript"></script>
<script>
$("#id_user").css("display","none")
            .val({{request.user.id}})
$("#id_auto_password").css("display","none")    

$("#id_config_mail").change(function (e){
	if ($("#id_config_mail option").filter(':selected').val() == "configure"){
	$("#reg_comp #form_css div:nth-child(n+7):nth-child(-n+13)").css("display","block")
}else{
	$("#reg_comp #form_css div:nth-child(n+7):nth-child(-n+13)").css("display","none")
}
});



window.onload = function () {
		$("div .form-group").addClass("form-floating mb-3");
		$("div .form-floating input").addClass("form-control");
		$("div .form-floating input").attr("placeholder", "RANDOM");
		$("#id_config_mail option:first-child").text("Select one configuration to use e-mail customize app").attr('value', 'default');
		$("#id_config_mail").addClass("form-select")
		$("#id_require_tls").addClass("form-select")
		$("#id_require_tls option:first-child").text("Require TLS?").attr('selected', 'selected');
		$("#id_require_tls").css("margin-bottom","10px")
		$("#id_host_password").attr("type","password")

		if ($("#id_config_mail option").filter(':selected').val() == "configure"){
	$("#reg_comp #form_css div:nth-child(n+7):nth-child(-n+13)").css("display","block")
}else{
	$("#reg_comp #form_css div:nth-child(n+7):nth-child(-n+13)").css("display","none")
}
}

$("#providers").change(function(e){
  provider = $("#providers").find(":selected").val()
  $("#id_port_server").val('587')
  $("#id_require_tls").val('true').change()
  $("#id_host_user").val($("#id_email").val())

  if (provider == 'gmail'){
  	$("#id_smtp_server").val('smtp.gmail.com')
  	$("#id_require_tls").val('true').change()
  }
  else if(provider == 'outlook'){
  	$("#id_smtp_server").val('smtp.office365.com')
  	$("#id_require_tls").val('true').change()
  }
  else if(provider == 'msn'){
  	$("#id_smtp_server").val('smtp-mail.outlook.com')
  	$("#id_require_tls").val('true').change()
  }
  else if(provider == 'yahoo'){
  	$("#id_smtp_server").val('smtp.mail.yahoo.com')
  	$("#id_require_tls").val('true').change()
  }
  else if(provider == 'expressoMG'){
  	$("#id_smtp_server").val('smtp.expresso.mg.gov.br')
  	$("#id_host_user").parents().css('display','block')
  	$("#id_require_tls").val('true').change()
  }
  else if(provider == 'locaweb'){
  	$("#id_smtp_server").val('email-ssl.com.br')
  	$("#id_port_server").val('465')
  }
  
  else if(provider == 'another'){
  	$("#reg_comp #form_css div:nth-child(n+7):nth-last-child(n+2)").css("display","block")
  	$("#id_smtp_server").val('')
  	$("#id_port_server").val('')
  	$("#id_require_tls").val('unknown').change()
  	$("#id_host_user").val('')
  }
});

function catch_provider(e){
	e.preventDefault()
	provider = $("#id_email").val().split("@")[1]
	config = $("#id_config_mail option").filter(':selected').val()
	if (config == "default" || config == ""){
		$("#id_config_mail").val('3').change();
		config == "forward"
	}
	if (provider == 'gmail.com' && config != "forward"){
		response_form = window.confirm("If you want to register the provider 'gmail.com' make sure you have entered the app password. If you have configured click 'OK' if not enter the link -> https://support.google.com/accounts/answer/185833");
		if (response_form == true){
			$("#reg_comp").submit()
		}
	}
	else{
		$("#reg_comp").submit()
	}
}

    
</script>
{% endblock %}